# Joint limits for tractor model
joint_limits:
  front_steer_joint:
    has_position_limits: true
    min_position: -0.785  # -45 degrees (-PI/4)
    max_position: 0.785   # 45 degrees (PI/4)
    has_velocity_limits: true
    max_velocity: 1.0     # rad/s
    has_acceleration_limits: true
    max_acceleration: 0.5 # rad/s^2
    has_effort_limits: true
    max_effort: 100       # Nm